package telas;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import classes.Novato;

/**
 *
 * @author Isabelle
 */
public class Cadastro extends javax.swing.JFrame {

    //Mapa mapa;
    /**
     * Creates new form Cadastro
     */
    public Cadastro(char cursovindo) {
        initComponents();
        if (cursovindo == 'a') {
        } else if (cursovindo == 'i') {
            inform.doClick();
        } else if (cursovindo == 'e') {
            eletro.doClick();
        } else if (cursovindo == 'v') {
            vestu.doClick();
        } else if (cursovindo == 't') {
            text.doClick();
        }
        //NOVA FONTE ADICIONADA:
        try {
            Font novaFonte = Font.createFont(Font.TRUETYPE_FONT, new File("alamain1.ttf")).deriveFont(100f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("alamain1.ttf")));
            jLabel3.setFont(novaFonte);

        } catch (IOException | FontFormatException e) {
            e.printStackTrace();
        }
    }

//    @Override
//    public void dispose() {
//        super.dispose();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        curso = new javax.swing.ButtonGroup();
        deuses = new javax.swing.ButtonGroup();
        animais = new javax.swing.ButtonGroup();
        virtude = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inform = new javax.swing.JRadioButton();
        eletro = new javax.swing.JRadioButton();
        text = new javax.swing.JRadioButton();
        vestu = new javax.swing.JRadioButton();
        PRONTO = new javax.swing.JButton();
        teste = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        afrodite = new javax.swing.JRadioButton();
        hermes = new javax.swing.JRadioButton();
        apolo = new javax.swing.JRadioButton();
        ares = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        tigre = new javax.swing.JRadioButton();
        aguia = new javax.swing.JRadioButton();
        golfinho = new javax.swing.JRadioButton();
        cavalo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        empatia = new javax.swing.JRadioButton();
        generosidade = new javax.swing.JRadioButton();
        confianca = new javax.swing.JRadioButton();
        determinacao = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        facil = new javax.swing.JRadioButton();
        medio = new javax.swing.JRadioButton();
        dificil = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1323, 640));

        jPanel1.setBackground(new java.awt.Color(91, 86, 80));
        jPanel1.setForeground(new java.awt.Color(224, 221, 221));
        jPanel1.setPreferredSize(new java.awt.Dimension(1323, 640));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nick:");

        txtNome.setBackground(new java.awt.Color(244, 243, 240));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seu curso:");

        curso.add(inform);
        inform.setForeground(new java.awt.Color(224, 221, 221));
        inform.setText("Informática");
        inform.setContentAreaFilled(false);

        curso.add(eletro);
        eletro.setForeground(new java.awt.Color(224, 221, 221));
        eletro.setText("Eletrotécnica");
        eletro.setContentAreaFilled(false);

        curso.add(text);
        text.setForeground(new java.awt.Color(224, 221, 221));
        text.setText("Têxtil");
        text.setContentAreaFilled(false);

        curso.add(vestu);
        vestu.setForeground(new java.awt.Color(224, 221, 221));
        vestu.setText("Vestuário");
        vestu.setContentAreaFilled(false);

        PRONTO.setBackground(new java.awt.Color(255, 255, 255));
        PRONTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imagens/botaopronto.jpg"))); // NOI18N
        PRONTO.setBorder(null);
        PRONTO.setBorderPainted(false);
        PRONTO.setContentAreaFilled(false);
        PRONTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRONTOMouseClicked(evt);
            }
        });
        PRONTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRONTOActionPerformed(evt);
            }
        });

        teste.setBackground(new java.awt.Color(255, 255, 255));
        teste.setForeground(new java.awt.Color(124, 161, 200));
        teste.setText("(Não sabe?)");
        teste.setBorder(null);
        teste.setBorderPainted(false);
        teste.setContentAreaFilled(false);
        teste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testeMouseClicked(evt);
            }
        });
        teste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testeActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(91, 86, 80));
        jLabel3.setFont(new java.awt.Font("Alamain", 0, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 199, 140));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("cadastro");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Uma divindade grega:");

        deuses.add(afrodite);
        afrodite.setForeground(new java.awt.Color(224, 221, 221));
        afrodite.setText("Afrodite");
        afrodite.setContentAreaFilled(false);

        deuses.add(hermes);
        hermes.setForeground(new java.awt.Color(224, 221, 221));
        hermes.setText("Hermes");
        hermes.setContentAreaFilled(false);

        deuses.add(apolo);
        apolo.setForeground(new java.awt.Color(224, 221, 221));
        apolo.setText("Apolo");
        apolo.setContentAreaFilled(false);

        deuses.add(ares);
        ares.setForeground(new java.awt.Color(224, 221, 221));
        ares.setText("Ares");
        ares.setContentAreaFilled(false);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Um animal:");

        animais.add(tigre);
        tigre.setForeground(new java.awt.Color(224, 221, 221));
        tigre.setText("Tigre");
        tigre.setContentAreaFilled(false);

        animais.add(aguia);
        aguia.setForeground(new java.awt.Color(224, 221, 221));
        aguia.setText("Águia");
        aguia.setContentAreaFilled(false);

        animais.add(golfinho);
        golfinho.setForeground(new java.awt.Color(224, 221, 221));
        golfinho.setText("Lobo");
        golfinho.setContentAreaFilled(false);

        animais.add(cavalo);
        cavalo.setForeground(new java.awt.Color(224, 221, 221));
        cavalo.setText("Cavalo");
        cavalo.setContentAreaFilled(false);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Uma virtude:");

        virtude.add(empatia);
        empatia.setForeground(new java.awt.Color(224, 221, 221));
        empatia.setText("Empatia");
        empatia.setContentAreaFilled(false);

        virtude.add(generosidade);
        generosidade.setForeground(new java.awt.Color(224, 221, 221));
        generosidade.setText("Generosidade");
        generosidade.setContentAreaFilled(false);

        virtude.add(confianca);
        confianca.setForeground(new java.awt.Color(224, 221, 221));
        confianca.setText("Confiança");
        confianca.setContentAreaFilled(false);

        virtude.add(determinacao);
        determinacao.setForeground(new java.awt.Color(224, 221, 221));
        determinacao.setText("Determinação");
        determinacao.setContentAreaFilled(false);

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dificuldade:");

        buttonGroup1.add(facil);
        facil.setForeground(new java.awt.Color(224, 221, 221));
        facil.setText("Fácil");
        facil.setContentAreaFilled(false);

        buttonGroup1.add(medio);
        medio.setForeground(new java.awt.Color(224, 221, 221));
        medio.setText("Médio");
        medio.setContentAreaFilled(false);

        buttonGroup1.add(dificil);
        dificil.setForeground(new java.awt.Color(224, 221, 221));
        dificil.setText("Difícil (em andamento)");
        dificil.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNome))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(inform)
                                    .addGap(27, 27, 27)
                                    .addComponent(eletro))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(afrodite)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(tigre))
                                        .addComponent(empatia)
                                        .addComponent(facil))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(aguia)
                                        .addComponent(hermes)
                                        .addComponent(generosidade)
                                        .addComponent(medio))))
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(text)
                                        .addComponent(apolo))
                                    .addGap(68, 68, 68)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ares)
                                        .addComponent(vestu)))
                                .addComponent(dificil)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(golfinho)
                                        .addComponent(confianca))
                                    .addGap(48, 48, 48)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(determinacao)
                                        .addComponent(cavalo)))))
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(teste))
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(PRONTO)))
                .addGap(412, 412, 412))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(teste))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inform)
                    .addComponent(eletro)
                    .addComponent(text)
                    .addComponent(vestu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afrodite)
                    .addComponent(hermes)
                    .addComponent(apolo)
                    .addComponent(ares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tigre)
                    .addComponent(aguia)
                    .addComponent(golfinho)
                    .addComponent(cavalo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empatia)
                    .addComponent(generosidade)
                    .addComponent(confianca)
                    .addComponent(determinacao))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facil)
                    .addComponent(medio)
                    .addComponent(dificil))
                .addGap(26, 26, 26)
                .addComponent(PRONTO)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1323, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PRONTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRONTOActionPerformed
        boolean tudomarcado = true;

        int charme = 1;
        int agil = 1;
        int moral = 1;
        int pop = 1;

        Novato user = new Novato();
        String nome = txtNome.getText();

        if (nome.equals("")) {
            tudomarcado = false;
        }
        user.setNome(nome);

        if (inform.isSelected()) {
            user.setCurso('i');
            moral++;
        } else if (eletro.isSelected()) {
            user.setCurso('e');
            pop++;
        } else if (vestu.isSelected()) {
            user.setCurso('v');
            charme++;
        } else if (text.isSelected()) {
            user.setCurso('t');
            agil++;
        } else {
            tudomarcado = false;
        }

        if (afrodite.isSelected()) {
            charme += 1;
        } else if (apolo.isSelected()) {
            pop += 1;
        } else if (hermes.isSelected()) {
            agil += 1;
        } else if (ares.isSelected()) {
            moral += 1;
        } else {
            tudomarcado = false;
        }

        if (aguia.isSelected()) {
            moral += 1;
        } else if (cavalo.isSelected()) {
            agil += 1;
        } else if (tigre.isSelected()) {
            charme += 1;
        } else if (golfinho.isSelected()) {
            pop += 1;
        } else {
            tudomarcado = false;
        }

        if (empatia.isSelected()) {
            moral += 1;
        } else if (determinacao.isSelected()) {
            agil += 1;
        } else if (generosidade.isSelected()) {
            pop += 1;
        } else if (confianca.isSelected()) {
            charme += 1;
        } else {
            tudomarcado = false;
        }

        if (facil.isSelected()) {
            user.setNivel('f');
        } else if (medio.isSelected()) {
            user.setNivel('m');
        } else if (dificil.isSelected()) {
            user.setNivel('d');
        } else {
            tudomarcado = false;
        }

        //no final, add td de uma vez pro usuario com as somas
        user.setNivCharme(charme);
        user.setNivMoral(moral);
        user.setNivAgilidade(agil);
        user.setNivPop(pop);
//        } else {
//         tudomarcado = false;   
//        }
        if (tudomarcado == false) {
            JOptionPane.showMessageDialog(this, "Preencha todos os dados.");
        } else {
            dispose();
            Mapa t = new Mapa(user);
            t.setVisible(true);
        }

    }//GEN-LAST:event_PRONTOActionPerformed

    private void PRONTOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRONTOMouseClicked

    }//GEN-LAST:event_PRONTOMouseClicked

    private void testeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testeActionPerformed

        TelaTeste t = new TelaTeste();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_testeActionPerformed

    private void testeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testeMouseClicked
        Novato user = new Novato();
        String nome = txtNome.getText();
        user.setNome(nome);
    }//GEN-LAST:event_testeMouseClicked

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PRONTO;
    private javax.swing.JRadioButton afrodite;
    private javax.swing.JRadioButton aguia;
    private javax.swing.ButtonGroup animais;
    private javax.swing.JRadioButton apolo;
    private javax.swing.JRadioButton ares;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cavalo;
    private javax.swing.JRadioButton confianca;
    private javax.swing.ButtonGroup curso;
    private javax.swing.JRadioButton determinacao;
    private javax.swing.ButtonGroup deuses;
    private javax.swing.JRadioButton dificil;
    private javax.swing.JRadioButton eletro;
    private javax.swing.JRadioButton empatia;
    private javax.swing.JRadioButton facil;
    private javax.swing.JRadioButton generosidade;
    private javax.swing.JRadioButton golfinho;
    private javax.swing.JRadioButton hermes;
    private javax.swing.JRadioButton inform;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton medio;
    private javax.swing.JButton teste;
    private javax.swing.JRadioButton text;
    private javax.swing.JRadioButton tigre;
    private javax.swing.JTextField txtNome;
    private javax.swing.JRadioButton vestu;
    private javax.swing.ButtonGroup virtude;
    // End of variables declaration//GEN-END:variables

}
