/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Isabelle
 */
public class Credits extends javax.swing.JFrame {

    /**
     * Creates new form Credits
     */
    public Credits() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            Font novaFonte = Font.createFont(Font.TRUETYPE_FONT, new File("Arctic.otf")).deriveFont(18f);
            Font novaFonteTit = Font.createFont(Font.TRUETYPE_FONT, new File("Arctic.otf")).deriveFont(24f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("Arctic.otf")));
            professor.setFont(novaFonteTit);
            componentes.setFont(novaFonteTit);            
            max.setFont(novaFonte);
            paula.setFont(novaFonte);
            elane.setFont(novaFonte);
            isabelle.setFont(novaFonte);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (FontFormatException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        elane = new javax.swing.JLabel();
        isabelle = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        componentes = new javax.swing.JLabel();
        professor = new javax.swing.JLabel();
        paula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(199, 172, 132));

        elane.setFont(new java.awt.Font("Arctic", 1, 18)); // NOI18N
        elane.setForeground(new java.awt.Color(51, 51, 51));
        elane.setText("paula mileny;");

        isabelle.setFont(new java.awt.Font("Arctic", 1, 18)); // NOI18N
        isabelle.setForeground(new java.awt.Color(51, 51, 51));
        isabelle.setText("elane eduarda.");

        max.setFont(new java.awt.Font("Arctic", 1, 18)); // NOI18N
        max.setForeground(new java.awt.Color(51, 51, 51));
        max.setText("max miller");

        componentes.setFont(new java.awt.Font("Arctic", 1, 24)); // NOI18N
        componentes.setForeground(new java.awt.Color(255, 255, 255));
        componentes.setText("COMPONENTES");

        professor.setFont(new java.awt.Font("Arctic", 1, 24)); // NOI18N
        professor.setForeground(new java.awt.Color(255, 255, 255));
        professor.setText("PROFESSOR");

        paula.setFont(new java.awt.Font("Arctic", 1, 18)); // NOI18N
        paula.setForeground(new java.awt.Color(51, 51, 51));
        paula.setText("isabelle queiroz;");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(componentes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(professor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(elane)
                    .addComponent(isabelle)
                    .addComponent(paula)
                    .addComponent(max))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professor, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(max))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(componentes)
                    .addComponent(paula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isabelle)
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel componentes;
    private javax.swing.JLabel elane;
    private javax.swing.JLabel isabelle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel max;
    private javax.swing.JLabel paula;
    private javax.swing.JLabel professor;
    // End of variables declaration//GEN-END:variables
}
