/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import classes.Novato;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Paula
 */
public class TelaTeste extends javax.swing.JFrame {

    /**
     * Creates new form TelaTeste
     */
    public TelaTeste() {
        initComponents();
        //NOVA FONTE ADICIONADA:
        try {
            Font novaFonte = Font.createFont(Font.TRUETYPE_FONT, new File("alamain1.ttf")).deriveFont(52f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("alamain1.ttf")));
            testedeap.setFont(novaFonte);
            
        } catch (IOException | FontFormatException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rd1 = new javax.swing.JRadioButton();
        rd2 = new javax.swing.JRadioButton();
        rd3 = new javax.swing.JRadioButton();
        rd4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rd5 = new javax.swing.JRadioButton();
        rd6 = new javax.swing.JRadioButton();
        rd7 = new javax.swing.JRadioButton();
        rd8 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rd9 = new javax.swing.JRadioButton();
        rd10 = new javax.swing.JRadioButton();
        rd11 = new javax.swing.JRadioButton();
        rd12 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rd13 = new javax.swing.JRadioButton();
        rd14 = new javax.swing.JRadioButton();
        rd15 = new javax.swing.JRadioButton();
        rd16 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rd17 = new javax.swing.JRadioButton();
        rd18 = new javax.swing.JRadioButton();
        rd19 = new javax.swing.JRadioButton();
        rd20 = new javax.swing.JRadioButton();
        testedeap = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(162, 174, 160));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 16)); // NOI18N
        jLabel3.setText("   Primeiramente, por que você foi para o IF?");

        buttonGroup1.add(rd1);
        rd1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd1.setText("mainha mandou");
        rd1.setOpaque(false);
        rd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd2);
        rd2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd2.setText("disseram q tem nescau no lanche");
        rd2.setOpaque(false);

        buttonGroup1.add(rd3);
        rd3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd3.setText("melhor escola de caicó né mores?");
        rd3.setOpaque(false);

        buttonGroup1.add(rd4);
        rd4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd4.setText("minha trupe do fundamental disse q ia");
        rd4.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 16)); // NOI18N
        jLabel4.setText("   Em qual aspecto acadêmico você se sente mais confiante?");

        buttonGroup2.add(rd5);
        rd5.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd5.setText("lógica");
        rd5.setOpaque(false);

        buttonGroup2.add(rd6);
        rd6.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd6.setText("cálculo");
        rd6.setOpaque(false);

        buttonGroup2.add(rd7);
        rd7.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd7.setText("criatividade");
        rd7.setOpaque(false);

        buttonGroup2.add(rd8);
        rd8.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd8.setText("decorar informação");
        rd8.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("OCR A Extended", 1, 16)); // NOI18N
        jLabel6.setText("   Com qual área você mais se identifica?");

        buttonGroup3.add(rd9);
        rd9.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd9.setText("humanas");
        rd9.setOpaque(false);

        buttonGroup3.add(rd10);
        rd10.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd10.setText("exatas");
        rd10.setOpaque(false);

        buttonGroup3.add(rd11);
        rd11.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd11.setText("biológicas");
        rd11.setOpaque(false);

        buttonGroup3.add(rd12);
        rd12.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd12.setText("cachaças");
        rd12.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("OCR A Extended", 1, 16)); // NOI18N
        jLabel7.setText("   Dentre essas, qual matéria você prefere se aprofundar?");

        buttonGroup4.add(rd13);
        rd13.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd13.setText("química");
        rd13.setOpaque(false);

        buttonGroup4.add(rd14);
        rd14.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd14.setText("matemática");
        rd14.setOpaque(false);

        buttonGroup4.add(rd15);
        rd15.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd15.setText("física");
        rd15.setOpaque(false);

        buttonGroup4.add(rd16);
        rd16.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd16.setText("artes");
        rd16.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 16)); // NOI18N
        jLabel2.setText("   Qual é o seu IFesporte favorito?");

        buttonGroup5.add(rd17);
        rd17.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd17.setText("totó");
        rd17.setOpaque(false);

        buttonGroup5.add(rd18);
        rd18.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd18.setText("prings prongs");
        rd18.setOpaque(false);

        buttonGroup5.add(rd19);
        rd19.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd19.setText("peteca");
        rd19.setOpaque(false);

        buttonGroup5.add(rd20);
        rd20.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rd20.setText("esconde-esconde (versão ricardo ta vindo)");
        rd20.setOpaque(false);

        testedeap.setFont(new java.awt.Font("Alamain", 0, 52)); // NOI18N
        testedeap.setForeground(new java.awt.Color(255, 255, 255));
        testedeap.setText(" teste de aptidao");

        btnContinuar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnContinuar.setText("Pronto");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rd3)
                            .addComponent(rd1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rd5)
                                .addComponent(rd8)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rd9)
                                        .addComponent(rd10)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rd18)
                                                .addComponent(rd17))
                                            .addGap(147, 147, 147))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rd13)
                                                .addComponent(rd14))
                                            .addGap(172, 172, 172))))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rd7)
                                    .addComponent(rd6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rd16)
                                            .addComponent(rd15))))
                                .addGap(236, 236, 236))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rd12)
                                            .addComponent(rd11)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rd4)
                                            .addComponent(rd2))))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rd19)
                                    .addComponent(rd20)))))
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(testedeap, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnContinuar)
                        .addGap(33, 33, 33))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(testedeap)
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rd4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rd2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rd1)
                        .addGap(5, 5, 5)
                        .addComponent(rd3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addComponent(rd6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(rd11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addComponent(rd15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rd19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rd5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd8)
                        .addGap(42, 42, 42)
                        .addComponent(rd9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd10)
                        .addGap(42, 42, 42)
                        .addComponent(rd13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd14)
                        .addGap(42, 42, 42)
                        .addComponent(rd17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd18)))
                .addGap(18, 18, 18)
                .addComponent(btnContinuar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        boolean tudoM = true;
        String resultado="";
        char res ='x';
        int t = 0, i = 0, v = 0, e = 0;
        if(rd1.isSelected()){
            i +=1;
        }else if (rd2.isSelected()){
            t +=1;
        }else if (rd3.isSelected()){
            v += 1;
        }else if (rd4.isSelected()){
            e +=1;
        }else{
            tudoM = false;
        }
        
        if(rd5.isSelected()){
            i+=1;
        }else if (rd6.isSelected()){
            e +=1;
        }else if (rd7.isSelected()){
            v += 1;
        }else if (rd8.isSelected()){
            t +=1;
        }else{
            tudoM = false;
        }
        
        if (rd9.isSelected()){
            v+=1;
            t+=1;
        }else if (rd10.isSelected()){
            i +=1;
            e +=1;
        }else if(rd11.isSelected()){
            t +=1;
            v +=1;
        }else if (rd12.isSelected()){
            i +=1;
            e +=1;
        }else{
            tudoM =false;
        }
        
        if (rd13.isSelected()){
            t +=1;
        }else if (rd14.isSelected()){
            i +=1;
        }else if (rd15.isSelected()){
            e +=1;
        }else if(rd16.isSelected()){
            v += 1;
        }else{
            tudoM =false;
        }
        
        if (rd17.isSelected()){
            e +=1;
            i +=1;
        }else if(rd18.isSelected()){
            v +=1;
            e +=1;
        }else if (rd19.isSelected()){  
            i +=1;
            t +=1;
        }else if (rd20.isSelected()){
            t +=1;
            v+= 1;
        }else{
            tudoM =false;
        }
        Novato user = new Novato();
        int charme = 0, pop = 0, agil = 0,moral =0;
        
        int maior = 0;
        int vetor[]= new int[4];
        vetor[0] = i; vetor[1] = e; vetor[2] = v; vetor[3] = t;
        for (int a = 0; a < 4; a++) {  
            if(vetor[a] > maior){  
                maior = vetor[a];
            }else if(maior==i){
               resultado = "Parabéns, você é de Informática!"; 
               res ='i';
            }
            else if(maior==e){
                res ='e';
                resultado = "Que pena, você é de Eletrotécnica..."; 
            }
            else if(maior==v){
                res ='v';
                resultado = "Parabéns, você é de Vestuário!"; 
            }
            else if(maior==t){
                res ='t';
                resultado = "Parabéns, você é de Têxtil!"; 
            }
        }
       
        if (tudoM == false) {
            JOptionPane.showMessageDialog(this, "Selecione uma opção em cada pergunta.");
        } else {
            JOptionPane.showMessageDialog(this, resultado);
            dispose();
            Cadastro c = new Cadastro(res);
            c.setVisible(true);
            
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void rd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd10;
    private javax.swing.JRadioButton rd11;
    private javax.swing.JRadioButton rd12;
    private javax.swing.JRadioButton rd13;
    private javax.swing.JRadioButton rd14;
    private javax.swing.JRadioButton rd15;
    private javax.swing.JRadioButton rd16;
    private javax.swing.JRadioButton rd17;
    private javax.swing.JRadioButton rd18;
    private javax.swing.JRadioButton rd19;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JRadioButton rd20;
    private javax.swing.JRadioButton rd3;
    private javax.swing.JRadioButton rd4;
    private javax.swing.JRadioButton rd5;
    private javax.swing.JRadioButton rd6;
    private javax.swing.JRadioButton rd7;
    private javax.swing.JRadioButton rd8;
    private javax.swing.JRadioButton rd9;
    private javax.swing.JLabel testedeap;
    // End of variables declaration//GEN-END:variables
}
