/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Isabelle
 */
public class TelaGameOver extends javax.swing.JFrame {

    /**
     * Creates new form TelaGameOver
     */
    public TelaGameOver(char curso, float pont) {
        initComponents();
        switch (curso) {
            case 'i':
                txtGameOver.setText("Erro de sintaxe");
                break;
            case 'v':
                txtGameOver.setText("Perdeu a linha");
                break;
            case 't':
                txtGameOver.setText("Despadronizado");
                break;
            case 'e':
                txtGameOver.setText("Curto-Circuito");
                break;
        }
        txtPontuacaoFinal.setText("Seu lucro foi de "+pont);
        txtPontuacaoFinal2.setText("Sinceramente? Bem medíocre.");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sair = new javax.swing.JButton();
        txtPontuacaoFinal2 = new javax.swing.JTextField();
        txtPontuacaoFinal = new javax.swing.JTextField();
        txtGameOver = new javax.swing.JTextField();
        fundoooo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(976, 568));
        setSize(new java.awt.Dimension(976, 568));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sair.setBackground(new java.awt.Color(255, 255, 255));
        sair.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        sair.setForeground(new java.awt.Color(70, 53, 53));
        sair.setText("SAIR");
        sair.setContentAreaFilled(false);
        sair.setFocusPainted(false);
        sair.setOpaque(true);
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jPanel1.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 100, 30));

        txtPontuacaoFinal2.setEditable(false);
        txtPontuacaoFinal2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        txtPontuacaoFinal2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPontuacaoFinal2.setBorder(null);
        jPanel1.add(txtPontuacaoFinal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 500, 30));

        txtPontuacaoFinal.setEditable(false);
        txtPontuacaoFinal.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtPontuacaoFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPontuacaoFinal.setBorder(null);
        jPanel1.add(txtPontuacaoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 500, 60));

        txtGameOver.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        txtGameOver.setForeground(new java.awt.Color(255, 255, 255));
        txtGameOver.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGameOver.setBorder(null);
        txtGameOver.setOpaque(false);
        jPanel1.add(txtGameOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 950, 140));

        fundoooo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/01010.jpg"))); // NOI18N
        jPanel1.add(fundoooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);

    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundoooo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sair;
    private javax.swing.JTextField txtGameOver;
    private javax.swing.JTextField txtPontuacaoFinal;
    private javax.swing.JTextField txtPontuacaoFinal2;
    // End of variables declaration//GEN-END:variables
}
